Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - '**/*.gemspec'
  ExcludedMethods:
    - 'included' # ActiveSupport concerns
    - 'namespace' # rake tasks
    - 'task' # rake tasks

Metrics/LineLength:
  Max: 100

Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: required

Style/Documentation:
  Enabled: false

# More info: More info: https://github.com/rubocop-hq/ruby-style-guide/issues/556
Style/ModuleFunction:
  Enabled: false
