version: 2.1

jobs:
  lint:
    docker:
      - image: cimg/ruby:2.7.1
    steps:
      - checkout
      - restore_cache: &restore_cache
          name: Restore Bundle Cache
          keys:
            - codecademy-style-gem-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - codecademy-style-gem-{{ .Branch }}
            - codecademy-style-gem-main
            - codecademy-style-gem-
      - run: &bundle_install
          command: bundle install --path vendor/bundle
      - save_cache: &save_cache
          name: Store Bundle Cache
          key: codecademy-style-gem-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Run Rubocop
          command: bundle exec rubocop --config ./.rubocop.yml

workflows:
  version: 2
  lint:
    jobs:
      - lint
