name: Lint

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint the app
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Ruby 
      uses: ruby/setup-ruby@v1 # no need for ruby-version because we have a .ruby_version file
      with:
        bundler-cache: true
  
    - name: Run Rubocop
      run: bundle exec rubocop --config ./.rubocop.yml
